### ISSUE TITLE
Overriding default settings not possible in Craft 3 beta 8

### ISSUE THREAD

**Issue by connor-baer** [nystudio107/craft3-imageoptim#3]
Overriding the default plugin settings with a `imageoptim.php` file in the `craft/config` folder throws an error: `Call to a member function setAttributes() on null`.

Looking at the updated [plugin settings documentation](https://github.com/craftcms/docs/blob/master/en/plugin-settings.md), it seems you're missing the `createSettingsModel()` method on the main plugin class. Will test and submit a pull request if it fixes the error.

**Comment by khalwat** [comment]
Ooops, thank you!

**Comment by khalwat** [comment]
Fixed in 1.0.6
